---
title: "Untitled"
author: "JJW"
date: "26/07/2020"
output: html_document
---

```{r}
library(tidyverse)
library(here)
library(magrittr)
library(janitor)
```

```{r}
all_data<-read.csv(here::here("data", "manipulation_data", "factors_Xinyi_Jonny_Combined2.csv"))

```

```{r}
all_data%<>%row_to_names(row_number = 1)

species_data<-all_data[,c(8,9)]



colnames(species_data)[1]<-"Host_species"
colnames(species_data)[2]<-"Spillover_species"

species_data$Host_species%<>%as.character()
species_data$Spillover_species%<>%as.character()



s <- strsplit(species_data$Host_species, split = ", ")
new11<-data.frame(Spillover_species = rep(species_data$Spillover_species, sapply(s, length)), Host_species = unlist(s))

new11$Host_species%<>%as.character()

s2 <- strsplit(new11$Host_species, split = ",")
new1<-data.frame(Spillover_species = rep(new11$Spillover_species, sapply(s2, length)), Host_species = unlist(s2))

new1$Host_species%<>%as.character()
t <- strsplit(new1$Host_species, split = " and ")
new2<-data.frame(Spillover_species = rep(new1$Spillover_species, sapply(t, length)), Host_species = unlist(t))

new2$Spillover_species%<>%as.character()

u <- strsplit(new2$Spillover_species, split = ", ")
new3<-data.frame(Host_species = rep(new2$Host_species, sapply(u, length)), Spillover_species = unlist(u))

new3$Spillover_species%<>%as.character()

v <- strsplit(new3$Spillover_species, split = " and ")
new44<-data.frame(Host_species = rep(new3$Host_species, sapply(v, length)), Spillover_species = unlist(v))

new44$Spillover_species%<>%as.character()

x <- strsplit(new44$Spillover_species, split = ";")
new4<-data.frame(Host_species = rep(new44$Host_species, sapply(x, length)), Spillover_species = unlist(x))

```
```{r}
new4$Host_species%<>%as.character() #we had 17 levels for tranmsission, summarised intpo 3 levels
new4$Host_species[grep("oar", new4$Host_species)] <- "Wild boar" 
new4$Host_species[grep("attle", new4$Host_species)] <- "Cattle" 
new4$Host_species[grep("ig", new4$Host_species)] <- "Pigs" 
new4$Host_species[grep("swine", new4$Host_species)] <- "Pigs" 
new4$Host_species[grep("African", new4$Host_species)] <- "African buffalo" 
new4$Host_species[grep("ison", new4$Host_species)] <- "American bison" 
new4$Host_species[grep("red deer", new4$Host_species)] <- "Red deer" 
new4$Host_species[grep("eep", new4$Host_species)] <- "Sheep" 
new4$Host_species[grep("ampire", new4$Host_species)] <- "Vampire bat" 


```
```{r}

new4 %<>% mutate(Host_species=recode(Host_species, "elk"= "Elk", "Foxes" = "Fox", "White-tailed Deer"="White-tailed deer", "dogs"="Dog", "Stray dogs"="Dog", " Impala antelope"="Impala", "\npolecat"="Polecat", "Humans"="Human", "Mule Deer"="Mule deer", "Marten"="Pine marten", "Kudu antelope "="Kudu"))

new4$Host_species<-gsub("\\s*\\([^\\)]+\\)","",new4$Host_species)

capFirst <- function(s) {paste(toupper(substring(s, 1, 1)), substring(s, 2), sep = "")}

new4$Host_species <- capFirst(new4$Host_species)

new4$Host_species%<>%as.factor()
library(Hmisc)
filter_host<-subset(new4, Host_species %nin% c("Mosquito?", "Human", "Bat", "Wild deer?", "Wild mammals", "Wild ruminants", "","?","Birds","Wild birds", "Domestic mammals", "Domestic ruminants", "Domestic small ruminants","Unknown", "Humans" ))

```

```{r}
filter_host$Spillover_species%<>%as.character()

filter_host$Spillover_species[grep("oar", filter_host$Spillover_species)] <- "Wild boar" 
filter_host$Spillover_species[grep("attle", filter_host$Spillover_species)] <- "Cattle" 
filter_host$Spillover_species[grep("igs", filter_host$Spillover_species)] <- "Pig" 
filter_host$Spillover_species[grep("Buffalo", filter_host$Spillover_species)] <- "African buffalo" 
filter_host$Spillover_species[grep("dog", filter_host$Spillover_species)] <- "Dog"  
filter_host$Spillover_species[grep("red deer", filter_host$Spillover_species)] <- "Red deer" 
filter_host$Spillover_species[grep("eep", filter_host$Spillover_species)] <- "Sheep" 


filter_host$Spillover_species<-gsub("\\s*\\([^\\)]+\\)","",filter_host$Spillover_species)

filter_host$Spillover_species <- capFirst(filter_host$Spillover_species)

filter_host %<>% mutate(Spillover_species=recode(Spillover_species, "Roan\nantelope"= "Roan antelope", "Thomson's gazelle\ngazelles " = "Thomson's gazelle", "White-tailed Deer"="White-tailed deer", "Dogs"="Dog", "Exotic\nfallow deer"="Fallow deer", "Alpine chamois "="Alpine chamois", "Brazilian dwarf\nbrocket deer"="Brazilian dwarf brocket deer", "Domestic goats"="Goats", "Mongolian\ngazelles"="Mongolian gazelle", "Capra ibex"="Alpine ibex", "Cow"="Cattle", "Donkeys)"="Donkey", "Ibex"="Alpine ibex", "Goats"="Goat", "White-tailed deer "="White-tailed deer", "Feral Hog"="Wild hogs", "Lions"="Lion", "Marten"="Pine marten"  ))


filter_host$Spillover_species%<>%as.factor()

filter_spill<-subset(filter_host, Spillover_species %nin% c("Domestic ruminants" ))

filter_spill$Host_species%<>%as.character()
filter_spill$Spillover_species%<>%as.character()

filter_spill%<>%mutate(Host_species=recode(Host_species, "Kudu antelope "="Kudu"))

filter_spill<-subset(filter_spill, Host_species!=Spillover_species)

#come back and spread dom ruminants
```

```{r}
#add orders so can order network
orders1<-read.csv(here::here("data", "manipulation_data", "host_info.csv"))

orders1<-orders1[,c(1,3)]
orders1%<>%row_to_names(row_number = 1)
colnames(orders1)[1]<-"Host_species"
orders1$Host_species<- capFirst(orders1$Host_species)
orders1 %<>% mutate(Host_species=recode(Host_species, "Domestic cattle"= "Cattle", "Sheep (Ovies aries)" = "Sheep", "White tailed deer"="White-tailed deer", "Goats (Capra hircus)"="Goat", "Horses"="Horse", "Dogs"="Dog", "Pygmy brocket deer"="Brazilian dwarf brocket deer", "Domestic goats"="Goats", "Donkeys"="Donkey", " red deer"="Red deer", "Chamois"="Alpine chamois", "Domestic pigs"="Pigs"))

colnames(orders1)[1]<-"Host_species"
orders1$Host_species%<>%as.character()

orders2<-left_join(filter_spill, orders1)

orders2$Order%<>%as.character()

orders3<-orders2[order(orders2$Order, orders2$Host_species ),]


orders3%<>%group_by(Order)

hi_host<-unique(orders3$Host_species)

lo_host<-unique(orders3$Spillover_species)
```

```{r}



t2 <- table(filter_spill$Host_species,filter_spill$Spillover_species)



```

```{r}
library(bipartite)
visweb(t2)
plotweb(t3, text.rot = 90, col.interaction = "purple", col.high = c("blue", "red"), col.low = "red")
#try to make order grouped
sequence<-list(seq.higher=hi_host, seq.lower=lo_host)
#figure how to do sequnece
t3<-sortweb(t2, sort.order="seq", sequence=sequence)
png(here::here("results", "Host_reservoir_plot.png"))
plotweb(t2, text.rot = 90)
dev.off()


```

```{r}
library(bipartiteD3)
library(r2d3)
bipartite_D3(t2)
```