---
title: "Data_Screen"
author: "Jonathan Wilson"
date: "26/05/2020"
output: html_document
---

```{r}
library(here)
library(tidyverse)
library(visdat)
```
```{r}

Spillover1<-readxl::read_excel(here::here("Data","Virus_Spillover.xlsx"))



colnames(Spillover1)[11]<-"Host"

host_table<-table(unique(Spillover1$Host))


```

```{r}

Spillover2<-Spillover1%>%mutate(Farm=recode(Host, "Bos taurus"="Cattle", "Bubalus bubalis, Bos indicus, Bos taurus"="Cattle","Sus scrofa"="Swine",  "Equus caballus"="Horse"))  

FA<-c("Swine", "Pigs", "pigs", "orse", "attle")



Farm_animals<-filter(Spillover2, grepl(paste(FA, collapse="|"), Farm))



```


```{r}
All_associations<-read_csv(here::here("Data","associations.csv"))


FA2<-c("Sus_scrofa", "Ovis_aries", "Bos_taurus", "Equus caballus", "Capra_aegagrus", "Capra_hircus", "Bubalus_bubalis",  "Cervus_elaphus",  "Cervus_nippon",  "Cervus_timorensis", "Bos_mutus", "Equus_asinus")


#pull all interactions involving farm animasl listed above
Farm_animals2<-filter(All_associations, grepl(paste(FA2, collapse="|"), hHostNameFinal))
colnames(Farm_animals2)[1]<-"Virus"



#lets get a list of unique viruses known to infect farm animnals
farm_a<-as.data.frame(unique(Farm_animals2$Virus))
colnames(farm_a)[1]<-"Virus"
```

```{r}

#Farm_animals3<-Farm_animals2[,c(1,2)]

#farm_b<-inner_join(farm_a,Farm_animals3, by="Virus")
All_farm<-left_join(farm_a, Spillover1, by="Virus")

vis_miss(All_farm)

```

```{r}
All_features<-read_csv(here::here("Data", "viruses.csv"))
colnames(All_features)[1]<-"Viruses"

tryagain<-

```
a<-"hello"
a


